export const SET_CURRENT_CHAT_REQUEST = "SET_CURRENT_CHAT_REQUEST";
export const SET_CURRENT_CHAT_SUCCESS = "SET_CURRENT_CHAT_SUCCESS";
export const SET_CURRENT_CHAT_FAIL = "SET_CURRENT_CHAT_FAIL";

export const SET_SELECTED_CHAT_REQUEST = "SET_SELECTED_CHAT_REQUEST";
export const SET_SELECTED_CHAT_SUCCESS = "SET_SELECTED_CHAT_SUCCESS";
export const SET_SELECTED_CHAT_FAIL = "SET_SELECTED_CHAT_FAIL";

export const RENAME_GROUP_CHAT_REQUEST = "RENAME_GROUP_CHAT_REQUEST";
export const RENAME_GROUP_CHAT_SUCCESS = "RENAME_GROUP_CHAT_SUCCESS";
export const RENAME_GROUP_CHAT_FAIL = "RENAME_GROUP_CHAT_FAIL";


export const ADD_NEW_IN_GROUP_CHAT_REQUEST = "ADD_NEW_IN_GROUP_CHAT_REQUEST";
export const ADD_NEW_IN_GROUP_CHAT_SUCCESS = "ADD_NEW_IN_GROUP_CHAT_SUCCESS";
export const ADD_NEW_IN_GROUP_CHAT_FAIL = "ADD_NEW_IN_GROUP_CHAT_FAIL";

export const REMOVE_USER_GROUP_CHAT_REQUEST = "REMOVE_USER_GROUP_CHAT_REQUEST";
export const REMOVE_USER_GROUP_CHAT_SUCCESS = "REMOVE_USER_GROUP_CHAT_SUCCESS";
export const REMOVE_USER_GROUP_CHAT_FAIL = "REMOVE_USER_GROUP_CHAT_FAIL";