export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAIL = "USER_LOGOUT_FAIL";

export const USER_LOGOUT_SUCCESS_CHAT = "USER_LOGOUT_SUCCESS_CHAT";

export const USER_LOGOUT_SUCCESS_MESSAGE = "USER_LOGOUT_SUCCESS_MESSAGE";
export const USER_LEAVE_GROUP = "USER_LEAVE_GROUP";

export const NOTIFY_USER = "NOTIFY_USER";
export const USER_OPENED_NOTIFIED_CHAT = "USER_OPENED_NOTIFIED_CHAT";
